### ISSUE TITLE
Click on Agenda on home page -> we get the Speakers tab but when clicked it goes back to home page

### ISSUE THREAD

**Issue by smtalimett** [GoLangGirls/golanggirls.github.io#5] opened 2018-09-11 04:58 UTC

**Comment by prathamesh-sonpatki** [comment] 2018-09-11 09:45
I think this is right. There is no `Speakers` link on home page which is causing the confusion.

Closing this as duplicate of #4.

**Closed by prathamesh-sonpatki** 2018-09-11 09:45 UTC
